import React from 'react';
export const metadata = {
  title: 'Update Password || LugBand',
  description: 'Generated by create next app',
};
const UpdatePassword = () => {
  return <div>UpdatePassword</div>;
};

export default UpdatePassword;
