import ProfileInformation from '@/app/(root)/admin/account/page';

export const metadata = {
  title: 'Profile Information || LugBand',
  description: 'Generated by create next app',
};

const ProfileInformationWrapper = () => {
  return (
    <div>
      <ProfileInformation />
    </div>
  );
};

export default ProfileInformationWrapper;
