import React from 'react';
export const metadata = {
  title: 'Auth || LugBand',
  description: 'Generated by create next app',
};
const AuthLayout = ({ children }) => {
  return <div className="container mx-auto">{children}</div>;
};

export default AuthLayout;
