import React from 'react';

export const metadata = {
  title: 'Payment Method || LugBand',
  description: 'Generated by create next app',
};

const PaymentMethod = () => {
  return <div>PaymentMethod</div>;
};

export default PaymentMethod;
